// File: app/terms-of-service/page.tsx
// Copy this entire file to your app/terms-of-service/ directory

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50 py-12 px-4">
      <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-xl p-8 border border-gray-100">
        <h1 className="text-4xl font-bold text-gray-900 mb-6">Terms of Service</h1>
        <p className="text-sm text-gray-500 mb-8">
          Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </p>

        <div className="prose prose-gray max-w-none space-y-6">
          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing and using [Your App Name] ("the Service"), you accept and agree to be 
              bound by these Terms of Service. If you do not agree to these terms, please do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed">
              [Your App Name] is a [describe what your app does in 2-3 sentences]. 
              The Service provides [list key features and functionalities].
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">3. Use License</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3">3.1 Permitted Use</h3>
            <p className="text-gray-700 leading-relaxed mb-3">You are granted a limited, non-exclusive, 
            non-transferable license to:</p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>Use the Service for personal or commercial purposes</li>
              <li>[Specific permitted actions relevant to your app]</li>
              <li>[Other allowed uses]</li>
            </ul>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-4">3.2 Restrictions</h3>
            <p className="text-gray-700 leading-relaxed mb-3">You agree NOT to:</p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>Reverse engineer, decompile, or disassemble the Service</li>
              <li>Use the Service for illegal purposes</li>
              <li>Attempt to overwhelm or disrupt the Service (DoS attacks)</li>
              <li>Use automated scripts or bots excessively</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Upload malicious files or code</li>
              <li>Infringe on intellectual property rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">4. User Content</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3">4.1 Your Responsibility</h3>
            <p className="text-gray-700 leading-relaxed">
              You are solely responsible for [the type of content users provide to your app]. 
              You represent that you own or have the necessary rights to [use/upload/process] your content.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-4">4.2 Data Handling</h3>
            <p className="text-gray-700 leading-relaxed">
              [Explain how your app handles user content - e.g., "Files are processed in real-time and 
              NOT stored on our servers" OR "Content is stored securely with encryption"]
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">5. Intellectual Property</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              The Service, including its original content, features, and functionality, is owned by 
              [Your App Name] and is protected by international copyright, trademark, patent, 
              trade secret, and other intellectual property laws.
            </p>
            <p className="text-gray-700 leading-relaxed">
              You retain all rights to your uploaded content and any outputs generated by the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">6. Third-Party Services</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              The Service relies on third-party services, including:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>[List any third-party APIs or services your app uses]</li>
              <li>Cloud hosting providers</li>
            </ul>
            <p className="text-gray-700 leading-relaxed mt-3">
              We are not responsible for the availability, functionality, or policies of these third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">7. Disclaimers and Warranties</h2>
            
            <h3 className="text-xl font-semibold text-gray-800 mb-3">7.1 "AS IS" Basis</h3>
            <p className="text-gray-700 leading-relaxed">
              THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, 
              EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, 
              FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
            </p>

            <h3 className="text-xl font-semibold text-gray-800 mb-3 mt-4">7.2 No Guarantee</h3>
            <p className="text-gray-700 leading-relaxed">
              We do not guarantee that:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>The Service will be uninterrupted or error-free</li>
              <li>[App-specific functionality] will be 100% accurate</li>
              <li>The Service will meet your specific requirements</li>
              <li>[Other limitations specific to your app]</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">8. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, 
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR 
              REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, 
              OR OTHER INTANGIBLE LOSSES RESULTING FROM:
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4 mt-3">
              <li>Your use or inability to use the Service</li>
              <li>Any unauthorized access to your files or data</li>
              <li>Errors or inaccuracies in outputs</li>
              <li>Any interruption or cessation of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">9. Indemnification</h2>
            <p className="text-gray-700 leading-relaxed">
              You agree to indemnify, defend, and hold harmless [Your App Name] and its 
              affiliates from any claims, liabilities, damages, losses, and expenses arising from 
              your use of the Service or violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">10. Privacy</h2>
            <p className="text-gray-700 leading-relaxed">
              Your use of the Service is also governed by our Privacy Policy. Please review our 
              <a href="/privacy-policy" className="text-blue-600 hover:text-blue-800 mx-1">Privacy Policy</a>
              to understand our practices.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">11. Modifications to Service</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to modify, suspend, or discontinue the Service at any time without 
              notice. We will not be liable to you or any third party for any modification, suspension, 
              or discontinuation of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">12. Changes to Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to update these Terms at any time. We will notify users of any 
              material changes by posting the new Terms on this page with an updated "Last Updated" date.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">13. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], 
              without regard to its conflict of law provisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">14. Contact Information</h2>
            <p className="text-gray-700 leading-relaxed">
              For questions about these Terms, please contact us at:
            </p>
            <div className="bg-gray-50 p-4 rounded-lg mt-3">
              <p className="text-gray-700">
                <strong>Email:</strong> melodywebpages@gmail.com
              </p>
            </div>
          </section>

          <section className="mt-8 pt-6 border-t border-gray-200">
            <p className="text-sm text-gray-500">
              By using the Service, you acknowledge that you have read, understood, and agree to be 
              bound by these Terms of Service.
            </p>
          </section>
        </div>

        <div className="mt-8">
          <a 
            href="/"
            className="text-blue-600 hover:text-blue-800 font-medium"
          >
            ← Back to [Your App Name]
          </a>
        </div>
      </div>
    </main>
  );
}

